# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0002_auto_20160306_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='naver.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publishers/'),
        ),
    ]
